#! /bin/bash

# ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go)"

brew install git dash coreutils
brew install bash bash-completion z
# brew install mpop msmtp
# brew install mutt
# brew install slrn newsbeuter
# brew install rlwrap elinks # tmux
# brew install dict surfraw bc

# brew install ffmpeg
# brew tap pigoz/mplayer2
# brew install --HEAD pigoz/mplayer2/mplayer2

# brew install imagemagick media-info gifsicle
# brew install aria2 mldonkey
# brew install mpd mpc
# brew install dcraw gphoto2
# brew install cdrkit
# brew install cuetools shntool
# brew install flac mac id3v2
# brew install unrar p7zip
# brew install catdoc libplist libicns
# brew install detox duff dhex gcal
# brew install fortune figlet cowsay
# brew install youtube-dl nzbget

# sudo easy_install-3.2 pip
# sudo pip install colormath
# sudo pip install PyYAML
# sudo pip install Jinja2

cd "$HOME"

# wget ftp://ftp.gimp.org/pub/gimp/v2.8/osx/gimp-2.8.2-dmg-2.dmg
# wget http://audacity.googlecode.com/files/audacity-macosx-ub-2.0.3.dmg
wget http://downloads.sourceforge.net/jumpcut/Jumpcut_0.63.tgz
wget http://xee.googlecode.com/files/Xee2.2.zip
wget http://theunarchiver.googlecode.com/files/TheUnarchiver3.6.1.zip
wget http://pqrs.org/macosx/keyremap4macbook/files/KeyRemap4MacBook-8.0.0.dmg
# wget http://darcs.net/binaries/macosx/darcs-2.5-OSX-10.6-i386.tar.gz
# open http://www.libreoffice.org/download/?type=mac-x86
# owl install grabc ppsei darcs-bin
# owl install ttf-anonymous-pro ttf-dejavu ttf-droid ttf-envy-code-r ttf-freefont ttf-junicode ttf-liberation ttf-linux-libertine ttf-ms-fonts

git clone -b macosx git://github.com/baskerville/dotfiles.git .dotfiles
git clone -b macosx git://github.com/baskerville/bin.git .bin

cd "$HOME" && ln -s ".dotfiles/README.md" ".README.md"
cd "$HOME" && ln -s ".dotfiles/XCompose" ".XCompose"
cd "$HOME" && ln -s ".dotfiles/Xresources" ".Xresources"
cd "$HOME" && ln -s ".dotfiles/bash_profile" ".bash_profile"
cd "$HOME" && ln -s ".dotfiles/bashrc" ".bashrc"
cd "$HOME" && ln -s ".dotfiles/bcrc" ".bcrc"
cd "$HOME" && ln -s ".dotfiles/curlrc" ".curlrc"
cd "$HOME" && ln -s ".dotfiles/dhexrc" ".dhexrc"
cd "$HOME" && ln -s ".dotfiles/dircolors" ".dircolors"
cd "$HOME" && ln -s ".dotfiles/gitconfig" ".gitconfig"
cd "$HOME" && ln -s ".dotfiles/gtk2_gvim" ".gtk2_gvim"
cd "$HOME" && ln -s ".dotfiles/gtk2_settings" ".gtkrc-2.0"
cd "$HOME" && ln -s ".dotfiles/gvimrc" ".gvimrc"
cd "$HOME" && ln -s ".dotfiles/hgrc" ".hgrc"
cd "$HOME" && ln -s ".dotfiles/inputrc" ".inputrc"
cd "$HOME" && ln -s ".dotfiles/lftprc" ".lftprc"
cd "$HOME" && ln -s ".dotfiles/mailcap" ".mailcap"
cd "$HOME" && ln -s ".dotfiles/mpdconf" ".mpdconf"
cd "$HOME" && ln -s ".dotfiles/muttrc" ".muttrc"
cd "$HOME" && ln -s ".dotfiles/profile" ".profile"
cd "$HOME" && ln -s ".dotfiles/shell_aliases" ".shell_aliases"
cd "$HOME" && ln -s ".dotfiles/shell_functions" ".shell_functions"
cd "$HOME" && ln -s ".dotfiles/slrnrc" ".slrnrc"
cd "$HOME" && ln -s ".dotfiles/startpage.html" ".startpage"
cd "$HOME" && ln -s ".dotfiles/themes/slrn/slrn_theme" ".slrn_colors"
cd "$HOME" && ln -s ".dotfiles/tmux.conf" ".tmux.conf"
cd "$HOME" && ln -s ".dotfiles/toprc" ".toprc"
cd "$HOME" && ln -s ".dotfiles/vimrc" ".vimrc"
cd "$HOME" && ln -s ".dotfiles/xinitrc" ".xinitrc"
cd "$HOME" && ln -s ".dotfiles/xmodmaprc" ".xmodmaprc"
cd "$HOME" && ln -s ".wallpaper-light" ".wallpaper"
cd "$HOME" && ln -s "doc/books/" "books"
cd "$HOME" && ln -s "doc/notules/" "notules"
cd "$HOME" && ln -s "src/abs" "abs"
cd "$HOME" && ln -s "src/aur/" "aur"
cd "$HOME" && ln -s "src/lang/" "lang"
cd "$HOME" && ln -s "src/projects/" "projects"
cd "$HOME/.audacity-data/Theme" && ln -s "Gnome_ImageCache.png" "ImageCache.png"
cd "$HOME/.bin" && ln -s "/usr/bin/perl-rename" "pmv"
cd "$HOME/.bin" && ln -s "audio_player" "ap"
cd "$HOME/.bin" && ln -s "document_reader" "dr"
cd "$HOME/.bin" && ln -s "dvol_colors-light" "dvol_colors"
cd "$HOME/.bin" && ln -s "editor" "e"
cd "$HOME/.bin" && ln -s "fileinfo" "gi"
cd "$HOME/.bin" && ln -s "httpd_toggle" "ht"
cd "$HOME/.bin" && ln -s "image_viewer" "iv"
cd "$HOME/.bin" && ln -s "mutt_query" "mq"
cd "$HOME/.bin" && ln -s "open" "o"
cd "$HOME/.bin" && ln -s "open" "xdg-open"
cd "$HOME/.bin" && ln -s "panel_colors-light" "panel_colors"
cd "$HOME/.bin" && ln -s "show_xface_colors-light" "show_xface_colors"
cd "$HOME/.bin" && ln -s "video_player" "vp"
cd "$HOME/.bin" && ln -s "web_browser" "wb"
cd "$HOME/.config/newsbeuter" && ln -s "../../.dotfiles/newsbeuter_config" "config"
cd "$HOME/.dotfiles" && ln -s "override.css-light" "override.css"
cd "$HOME/.dotfiles/color_schemes" && ln -s "ivory-dark.yaml" "current-dark"
cd "$HOME/.dotfiles/color_schemes" && ln -s "ivory-light.yaml" "current-light"
cd "$HOME/.dotfiles/color_schemes" && ln -s "symbolic.yaml" "current-symbolic"
cd "$HOME/.dotfiles/terminal_colors" && ln -s "redef-light" "redef"
cd "$HOME/.dotfiles/terminal_colors" && ln -s "redef_console-light" "redef_console"
cd "$HOME/.dotfiles/terminal_colors" && ln -s "xresources-light" "xresources"
cd "$HOME/.local/share" && ln -s "../../.dotfiles/texmf/" "texmf"
cd "$HOME/.mplayer" && ln -s "../.dotfiles/mplayer_config" "config"
cd "$HOME/.mplayer" && ln -s "../.dotfiles/mplayer_keys" "input.conf"
cd "$HOME/.mutt" && ln -s "../.dotfiles/themes/mutt/mutt_theme" "theme"
cd "$HOME/.ncmpcpp" && ln -s "../.dotfiles/ncmpcpp_config" "config"
cd "$HOME/.ncmpcpp" && ln -s "../.dotfiles/ncmpcpp_keys" "bindings"
cd "$HOME/.slrn" && ln -s "../.dotfiles/slrn_macros/" "macros"
cd "$HOME/.themes/mango" && ln -s "../../.dotfiles/themes/fontforge/mango_fontforge" "mango_fontforge"
cd "$HOME/.vim/bundle" && ln -s "../../.dotfiles/vim-quirks/" "vim-quirks"
cd "$HOME/.vim/colors" && ln -s "../../.dotfiles/themes/vim/bubblegum.vim" "bubblegum.vim"
cd "$HOME/.vim/colors" && ln -s "../../.dotfiles/themes/vim/raven.vim" "raven.vim"
cd "$HOME/.vim/colors" && ln -s "../../.dotfiles/themes/vim/raven256.vim" "raven256.vim"
cd "$HOME/.vim/colors" && ln -s "../../.dotfiles/themes/vim/raven8.vim" "raven8.vim"
cd "$HOME/src" && ln -s "../.dotfiles/patches/" "patches"
