#! /bin/sh

brew install git
brew install curl
brew install coreutils
brew install bash bash-completion
brew install z
brew install unrar
brew install mpop msmtp
brew install mutt
brew install rlwrap elinks tmux
brew install dict surfraw bc

# brew install ffmpeg
brew tap pigoz/mplayer2
brew install --HEAD pigoz/mplayer2/mplayer2

brew install mpd mpc
brew install gphoto2
brew install cdrkit
brew install cuetools shntool
brew install mac libplist
brew install p7zip id3v2
brew install detox duff
brew install fortune figlet cowsay
brew install youtube-dl

sudo easy_install-3.2 pip
sudo pip install colormath
sudo pip install PyYAML
sudo pip install Jinja2

cd "$HOME"

# wget ftp://ftp.gimp.org/pub/gimp/v2.8/osx/gimp-2.8.2-dmg-2.dmg
# wget http://audacity.googlecode.com/files/audacity-macosx-ub-2.0.3.dmg
# wget http://downloads.sourceforge.net/jumpcut/Jumpcut_0.63.tgz
# wget http://xee.googlecode.com/files/Xee2.2.zip
# wget http://theunarchiver.googlecode.com/files/TheUnarchiver3.6.1.zip
open http://www.libreoffice.org/download/?type=mac-x86

# owl install paps-bskv compface-bskv
# owl install grabc ppsei darcs-bin
# owl install ttf-anonymous-pro ttf-dejavu ttf-droid ttf-envy-code-r ttf-freefont ttf-junicode ttf-liberation ttf-linux-libertine ttf-ms-fonts

git clone git://github.com/baskerville/dotfiles.git .dotfiles
git clone git://github.com/baskerville/bin.git .bindir
