#! /bin/dash

current=$(readlink -nse "$XDG_COLORS_DIR/redef")

if [ $? -eq 1 ] ; then
    echo "can't find the current color theme" >&2
    exit 1
fi

base=$(basename "$current")
bgtype=${base##*-}

if [ $# -gt 0 ] ; then
    bgtype=$1
else
    case "$bgtype" in
        dark)
            bgtype=light
            ;;
        light)
            bgtype=dark
            ;;
    esac
fi

setconfbg "$XDG_COLORS_DIR/redef" $bgtype
setconfbg "$XDG_DOTFILES_DIR/override.css" $bgtype

for pts in /dev/ttys??? ; do
    [ -w "$pts" ] && "$XDG_COLORS_DIR/redef" > "$pts"
done
